### ISSUE TITLE
Multiple Each for loops not running.

### ISSUE THREAD

**Issue by btreptel** [SerpicoProject/Serpico#233]
-------------------
## Assistance 
Thank you for this amazing app! Using this on a win 2012 Server for testing.

When entering the below script it only outputs the first two findings into the document and ignores the rest.

### Example Meta Script.

¬report/findings_list/findings¬
† translate(type,$up,$low)=translate('physical',$up,$low) †
πtitleπ
πoverviewπ	
πtitleπ
πremediationπ
≠
¬report/findings_list/findings¬
† translate(type,$up,$low)=translate('social engineering',$up,$low) †
πtitleπ
πoverviewπ	
πtitleπ
πremediationπ	
≠
¬report/findings_list/findings¬
† translate(type,$up,$low)=translate('wireless',$up,$low) †
πtitleπ
πoverviewπ	
πtitleπ
πremediationπ
¥

###### Output

It only gives me the results for the first two statements even tho I have multiple findings in social engineering & wireless :) 

I'm sure it's me not getting the code right but your help would be amazing :) 

#######Log output
RuntimeError - Found a top-level element w:p with null namespace URI
Found a top-level element w:sectPr with null namespace URI #

**Comment by BuffaloWill** [comment]
Hi @btreptel! It looks like you are missing a ≠ in the third loop. This should fix the issue.

Thanks!

**Comment by btreptel** [comment]
Hi @BuffaloWill Thank you but the issue still exists. I'm now trying:

¬report/findings_list/findings¬
† translate(type,$up,$low)=translate('physical',$up,$low) †
πtitleπ
πoverviewπ	
πtitleπ
πremediationπ
≠
¬report/findings_list/findings¬
† translate(type,$up,$low)=translate('social engineering',$up,$low) †
πtitleπ
πoverviewπ	
πtitleπ
πremediationπ	
≠
¬report/findings_list/findings¬
† translate(type,$up,$low)=translate('wireless',$up,$low) †
πtitleπ
πoverviewπ	
πtitleπ
πremediationπ
≠
¥

**Comment by BuffaloWill** [comment]
Moved to e-mail.
