### ISSUE TITLE
How to use meta language if for string comparison

### ISSUE THREAD

**Issue by Bevilacqua** [SerpicoProject/Serpico#308]
## Bug
It doesn't seem possible to compare a variable to a string literal

`† COMPANY_NAME = "Serpico" †
HELLO WORLD
¥`

This causes an error that says: `could not compile test expression company_name="Serpico"`

**Comment by BuffaloWill** [comment]
Hi @Bevilacqua, please check out the wiki. 

https://github.com/SerpicoProject/Serpico/wiki/Parsing-by-Assessment-Type-or-Performing-a-String-Comparison-in-a-Report

**Comment by Bevilacqua** [comment]
I tried the following things all resulting in errors:

- `†translate(company_name, $up, $low)=translate('Serpico', $up, $low)† HELLO WORLD ¥`
    - ERROR: Xpath error: Invalid Expression (arrow points to the single quote character)
- `†translate(company_name, $up, $low)=translate("Serpico", $up, $low)† HELLO WORLD ¥`
    - ERROR: Xpath error: Invalid Expression (arrow points to the double quote character)
- `†translate(company_name, $up, $low)=translate(String('Serpico'), $up, $low)† HELLO WORLD ¥`
    - ERROR: Xpath error: Invalid Expression (arrow points to the single quote character)
- `†translate(company_name, $up, $low)='SERPICO'† HELLO WORLD ¥`
    - ERROR: up is not a defined variable

Am I missing something?

**Comment by kelvinsilva** [comment]
I am also having this problem. Any fixes?

**Comment by Bevilacqua** [comment]
@BuffaloWill any ideas?

**Comment by frisch-raphael** [comment]
@BuffaloWill If there's no problem with their syntax, it might come from the bug that 4B3l0 corrected in #307

**Comment by Bevilacqua** [comment]
@frisch-raphael  are you referring to moving the low/up declarations to the top of the file? I actually already did that on my personal branch and am still having the issue (except for the last bullet point about up not being defined).

**Comment by Bevilacqua** [comment]
Just figured it out. Has nothing to do with the syntax of the test expression. MS Word 2016 added a weird extended ascii character instead of an actual single quote. 

For reference: The fix was as follows (_helpers/xslt_generation.rb_)[_2 occurrences]: 

```Ruby
# Fix for MS Word 2016: Word added trash characters instead of single quotation. Replace the characters.
 corrected_condition = condition.gsub(0xE2.chr, "\'").gsub(/[\x80-\xff]/, "")
 q << "<xsl:if test=\"#{CGI.escapeHTML(corrected_condition.downcase).gsub("&amp;","&")}\">"
```

**Comment by BuffaloWill** [comment]
Thanks for following up on this @Bevilacqua. I tested in Word 2016 and ran into the same issue.

I committed your fix and a new string comparison meta character to compensate for this. The wiki page is also uploaded:

https://github.com/SerpicoProject/Serpico/wiki/Parsing-by-Assessment-Type-or-Performing-a-String-Comparison-in-a-Report
